import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Inner Circle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-9 lg:px-[50px] overflow-x-hidden`}>
        <nav>
          <Navbar />
        </nav>
        {children}
      </body>
    </html>
  );
}
